### PR TITLE
fix: remove combat auto-respawn and cap repair event fanout

### LINKED ISSUE #38: Combat death paths still auto-respawn + excess TGSubsystemEvents
## Summary

Post-PR #34 trace comparison (6 deaths: 1 collision kill + 5 self-destructs, 3 ship types) confirms all 5 anomalies from #33 are fixed for self-destruct. However, two new issues were found:

1. **All 4 combat death paths still auto-respawn** (HIGH)
2. **Excess TGSubsystemEvent count overflows reliable queue** (MEDIUM)

## Previous Anomaly Status (PR #34)

| # | Anomaly | Status |
|---|---------|--------|
| 1 | ObjectExplodingEvent wrong fields | **FIXED** — all 6 events match stock exactly |
| 2 | DestroyObject (0x14) sent | **FIXED** — zero 0x14 during any death |
| 3 | Server auto-respawn after self-destruct | **FIXED** — zero server-initiated ObjCreateTeam |
| 4 | Wrong owner_slot/team in respawn | **FIXED** — moot, no auto-respawn |
| 5 | MissionInit totalSlots=1 | **FIXED** — now 7 (maxplayers=6+1) |

## NEW-1: Combat Death Auto-Respawn (HIGH)

**Stock behavior**: The stock dedicated server **NEVER** auto-respawns ships for ANY death type. All ObjCreateTeam (0x03) messages in the battle trace (33.5 min, 3 players, 59 deaths) are **client-initiated relays** through the server's star topology, NOT server-originated spawns.

Evidence: 62 ObjCreateTeam total = 3 initial spawns + 59 client-initiated respawns. Zero server-originated ObjCreateTeam after any death.

**OpenBC behavior**: PR #34 fixed self-destruct (`respawn_timer = 0.0f`), but all 4 combat death paths still set `respawn_timer = 5.0f`, causing server-initiated auto-respawn 5 seconds after death with `owner_slot=0` (host's slot — WRONG).

Collision kill from the new trace:
```
00:02:06.265  Ship destroyed by collision
00:02:11.265  S->C ObjCreateTeam [03 00 00 08 80 ...] owner_slot=0 (WRONG — should not exist)
```

**4 locations in `src/server/server_dispatch.c`** that need `respawn_timer = 5.0f` changed to `0.0f`:
- Beam fire kill path (~line 614)
- Torpedo hit kill path (~line 714)
- Collision target death path (~line 1480)
- Collision source death path (~line 1618)

**Fix**: Set `respawn_timer = 0.0f` (or remove the assignment) at all 4 locations. The client will return to ship selection and send its own ObjCreateTeam when the player picks a new ship.

## NEW-2: Excess TGSubsystemEvents / Reliable Queue Overflow (MEDIUM)

**52 warnings** during the session:
```
[WARN ] [send] reliable retransmit queue full or oversized payload (slot=1 len=17)
  -- message sent once, no retransmit
```

`generate_damage_events()` in `src/server/server_dispatch.c` (lines 242-265) iterates ALL subsystems and sends ET_ADD_TO_REPAIR_LIST for each damaged one. This produces 18-25 events per death (one per subsystem on Sovereign/Galaxy).

**Stock sends only 6 repair events** for primary subsystems:

4 immediate (with ObjectExplodingEvent):
- PowerReactor → RepairSubsystem
- ShieldGenerator → RepairSubsystem
- PhaserController → RepairSubsystem
- PulseWeapon → RepairSubsystem

2 late (at T+9.5s):
- PoweredSubsystem (EPS) → RepairSubsystem
- RepairSubsystem → RepairSubsystem

| Death Type | Ship | OpenBC Events | Stock Events |
|------------|------|---------------|--------------|
| Self-destruct | Sovereign | 25 | 6 |
| Self-destruct | Galaxy | 25 | — |
| Self-destruct | Warbird | 18 | — |
| Collision | Sovereign | 7 | — |

The reliable retransmit queue (`BC_RELIABLE_QUEUE_SIZE=16`) overflows. Messages that overflow are sent once but NOT queued for retransmit. On a real network with packet loss, the client may miss the ObjectExplodingEvent or ScoreChange.

**Fix options**:
- **Option A** (recommended): Filter `generate_damage_events()` to only send repair events for primary subsystem types, matching stock behavior
- **Option B** (pragmatic): Increase `BC_RELIABLE_QUEUE_SIZE` from 16 to 32+ in `include/openbc/reliable.h`

## Not An Issue

**StateUpdates during explosion**: Client continues sending StateUpdates for the dead ship during the explosion period. This matches stock behavior — the wreckage remains a game object for the 9.5-second explosion duration.

## References

- Issue #33 — original self-destruct bug report
- PR #34 — fix that resolved the first 5 anomalies

### PR DESCRIPTION
**Pull request by aurablacklight**
## Summary
Fixes both regressions documented in issue #38:
1. Server-side auto-respawn still triggered for combat deaths.
2. Damage repair-list event fanout could overflow reliable retransmit queue.

Fixes #38.

## Root Cause
- Four combat kill paths still assigned `respawn_timer = 5.0f`, which caused server-generated `ObjCreateTeam` spawns after death.
- `generate_damage_events()` emitted `ADD_TO_REPAIR_LIST` per damaged subsystem instance. On high-subsystem ships this produced 18-25 reliable PythonEvents in a single death burst.

### 1) Disable server auto-respawn for combat deaths
Updated all combat death branches in `src/server/server_dispatch.c` to clear respawn state instead of scheduling timer-based respawn:
- Beam kill path
- Torpedo kill path
- Collision target death path
- Collision source death path

Behavior now matches stock dedicated server expectations: respawn is client-initiated only.

### 2) Bound repair-list event fanout
In `src/server/server_dispatch.c`:
- Added `repair_event_bucket_for_type()`.
- Updated `generate_damage_events()` to send at most one `ADD_TO_REPAIR_LIST` per primary subsystem bucket:
  - `power`
  - `shield`
  - `phaser`
  - `pulse_weapon`
  - `repair`

This prevents per-bank event spam while preserving repair UI signaling.

## Tests
Updated `tests/test_self_destruct.c`:
- `self_destruct_pipeline_matches_stock`
  - now asserts bounded repair event fanout (`>0` and `<=6`) in addition to existing health/death ordering checks.
- Added `collision_death_no_auto_respawn_and_repair_events_bounded`
  - triggers deterministic lethal collision,
  - asserts no `DestroyObj`,
  - asserts no server-initiated `ObjCreateTeam` respawn,
  - asserts repair events remain bounded (`<=6`).

## Validation
- `make server`
- `make build/tests/test_self_destruct`
- `build/tests/test_self_destruct`
- Result: `3/3 tests passed`

### CODE REVIEW

**Comment by aurablacklight** [comment]
Addressed the latest review feedback with a follow-up commit on this PR.

What changed
- `repair_event_bucket_for_type()` no longer drops non-primary subsystem types.
- Non-primary types now map to a bounded shared `other` bucket.
- `generate_damage_events()` bucket tracking expanded from 5 -> 6 buckets.

Resulting behavior
- Still bounded fanout (`<= 6` buckets total):
  - `power`, `shield`, `phaser`, `pulse_weapon`, `repair`, `other`.
- Non-primary subsystem damage (e.g. hull/sensor/engines/torpedo_tube/tractor/cloak) now produces repair-list signaling via `other` instead of being silently skipped.

Validation rerun
- `build/tests/test_self_destruct`
- Result: `3/3 tests passed`

Commit
- `11d8c85 fix: preserve non-primary repair events with bounded other bucket`

File: src/server/server_dispatch.c [hunk 1]
```diff
@@ -285,34 +285,56 @@ static int send_health_update_full_cycle(int target_slot, bool flush_owner)
...
+{
+    bc_peer_t *target = &g_peers.peers[target_slot];
+    bc_ship_state_t *ship = &target->ship;
+    bool sent_bucket[6] = { false, false, false, false, false, false };
+
+    for (int i = 0; i < cls->subsystem_count && i < BC_MAX_SUBSYSTEMS; i++) {
+        int bucket = repair_event_bucket_for_type(cls->subsystems[i].type);
+        if (bucket < 0 || bucket >= (int)(sizeof(sent_bucket) / sizeof(sent_bucket[0])) ||
+            sent_bucket[bucket]) {
+            continue;
```
Comment (aurablacklight) [inline src/server/server_dispatch.c]: Worth noting: the dedup fires on the *first* damaged subsystem of each type in iteration order. So if a ship has 8 phaser banks and bank 0 was undamaged but bank 1 was, bank 1 gets the event. This is fine — the repair UI just needs to know "phasers are damaged", not which specific bank. The `bc_repair_add` call still correctly adds the specific subsystem index to the internal repair queue regardless of whether the event was sent.

File: src/server/server_dispatch.c [hunk 2]
```diff
@@ -656,17 +678,16 @@ static void apply_beam_damage(int shooter_slot, int target_slot)
...
-
-    }
-}
+        process_ship_kill(shooter_slot, target_slot, false);
+
+        /* Clear victim ship state and disable server auto-respawn.
+         * Client is responsible for initiating respawn via ObjCreateTeam. */
+        target->has_ship = false;
+        target->respawn_timer = 0.0f;
+        target->respawn_class = -1;
```
Comment (aurablacklight) [inline src/server/server_dispatch.c]: All four combat kill paths (beam, torpedo, collision-target, collision-source) now set `respawn_timer = 0.0f` and `respawn_class = -1`. This is correct — the tick loop in `main.c:832` (`if (rp->respawn_timer <= 0.0f) continue;`) will skip this peer entirely, preventing any server-initiated respawn. Consistent with the self-destruct path at line 1364 which already had this pattern.

File: tests/test_self_destruct.c [hunk 3]
```diff
@@ -126,9 +150,15 @@ TEST(self_destruct_pipeline_matches_stock)
...
-        if (msg[0] == BC_OP_PYTHON_EVENT && msg_len >= 25) {
+        if (msg[0] == BC_OP_PYTHON_EVENT && msg_len >= 17) {
             i32 factory_id = read_i32_le(msg + 1);
             i32 event_type = read_i32_le(msg + 5);
+            if (factory_id == BC_FACTORY_SUBSYSTEM_EVENT &&
+                event_type == BC_EVENT_ADD_TO_REPAIR) {
+                add_to_repair_events++;
+                continue;
+            }
+            if (msg_len < 25) continue;
```
Comment (aurablacklight) [inline tests/test_self_destruct.c]: Good fix on the message length threshold. The old code required `msg_len >= 25` for all PythonEvents, which silently skipped the 17-byte `ADD_TO_REPAIR_LIST` events. Now it correctly parses the shorter repair events first, then gates on `msg_len >= 25` only for `OBJECT_EXPLODING` which actually needs the extra fields (source_obj, dest_obj, lifetime).

File: tests/test_self_destruct.c [hunk 4]
```diff
@@ -162,6 +194,122 @@ TEST(self_destruct_pipeline_matches_stock)
...
+                got_exploding = true;
+            }
+        }
+    }
+
+    CHECK(got_exploding);
+    CHECK(got_score_change);
+    CHECK(!saw_destroy_obj);
+    CHECK(!saw_server_respawn);
+    CHECK(add_to_repair_events <= 6);
```
Comment (aurablacklight) [inline tests/test_self_destruct.c]: Correctly permissive: unlike the self-destruct test (which asserts `> 0` because zeroing all subsystems guarantees damage events), the collision test only asserts `<= 6` without requiring `> 0`. An environment collision with extreme force may kill the ship before subsystem-level damage granularity produces repair events, depending on how the damage cascade resolves. This avoids a flaky assertion.
